# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82a2fe94c4fbf98a33c3bf6435267ffb3e837eed9e43f5784e1e9740a1784adb6f29c34feca698212f975e4173c0b6d72b85d1730991b9cfd309cc3ec2f5efb0

test:
  secret_key_base: 935d78e53b90fe8b145a69446902597e3235e11eb58343b8f51ba1d6fa288da1ef5576d744d6832d4e4de336471d44778c53d43e0ef736e3a3697f1db527efc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
